[build]
builder = "nixpacks"
buildCommand = "cd agency.backend/agency.backend/backend && ./mvnw clean package -DskipTests"

[deploy]
startCommand = "cd agency.backend/agency.backend/backend && java -jar target/*.jar"
healthcheckPath = "/ping"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
