import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script"; // ✅ Import Script
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
  src="https://www.paypal.com/sdk/js?client-id=AcQpqkzCDAR2KEZdLgUzYC4hCDz-aFxblV2qH9cYLKPDs4rSJWFs6nLDP6jIG5b5MHsFP_t02pVU_hEy&currency=USD&components=buttons,funding-eligibility"
  data-sdk-integration-source="button-factory"
  strategy="afterInteractive"
/>


      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
